### ISSUE TITLE
'Amplificator' commit

### ISSUE THREAD

**Issue by JesterWizard** [MokhaLeee/fe8u-cskillsys-kernel#138]
I've checked several skills with this new amplificator formula now, and I'm not getting the expected results. On `Colossus` it adds 200 to `amplificator` but this doesn't change the base damage. The same with `Impale` where it adds 300 and my latest addition `SureStrike` (which boosts damage by 1.5x) which adds 75.

**Comment by MokhaLeee** [comment]
It's truly that it is wrong that `SID_Impale` should cause damage +300% rather than 400%, now fixed

**Comment by JesterWizard** [comment]
This is not fixed. You've misunderstood the issue. 

The calculation is not taking effect. 

Here's a video displaying the issue for Colossus (which you revised to use amplificator + 200). You can see that even with the skill proccing, Eirika still does her regular damage. 

https://github.com/MokhaLeee/fe8u-cskillsys-kernel/assets/164426396/9c7e7a7b-6508-442a-a947-786e50c2cae7

I believe the reason for this is because calculation is stuck inside `InfinityEdge` in `BattleHit.c`. After moving it outside, Colossus started applying the proper amount of damage.

![image](https://github.com/MokhaLeee/fe8u-cskillsys-kernel/assets/164426396/cf3630cd-34e1-44e0-be55-d7f659c12393)


And on the subject of the spelling of the word, we're both wrong. On googling it, it really should be `Amplifier`.
