### ISSUE TITLE
Text has disappeared

### ISSUE THREAD

**Issue by JesterWizard** [MokhaLeee/fe8u-cskillsys-kernel#177]
Okay this one is defintely more of a concern. All text from the game has been removed. Checking in FEBuilder, it's literally all gone.

![image](https://github.com/MokhaLeee/fe8u-cskillsys-kernel/assets/164426396/3746dae3-43ee-42e8-b8b5-b41b1f3c7622)

![image](https://github.com/MokhaLeee/fe8u-cskillsys-kernel/assets/164426396/40e574ad-90ce-44ef-9412-877c3b623b7e)

**Comment by MokhaLeee** [comment]
this is a feature rather than bug.  We just want to delete the text of the chapter that will not be used to save about 6KB memory.

**Comment by MokhaLeee** [comment]
The work of cutting text data is a key step to put kernel .text section into the in-BL range to improve performance. Since even just the .text section in kernel also needs a large stretches of space. And the space of text data in vanilla is the ideal in-BL range space. Thus we swapped this space to kernel's program.

> All the default text is wiped

This assertion is wrong, and we keep all the text data except for the dialogue and the world map text.

> What if you just want the vanilla rom with this skill system?

If you want to add vanilla dialogue, just import the text from 0x9000000 onwards and things will done.

> In no sane world is this a feature

This assertion needs to be discussed more broadly. At least I personally don't agree with that.

**Comment by JesterWizard** [comment]
> This assertion is wrong, we keep all the text data except for the dialogue and the world map text, which is just originally useless for new game developers.

That's the text I'm talking about. The dialogue is what I showed you in the screenshot. 

>If you want to add vanilla dialogue, you just manually import the text you want to the 0x9000000 onwards and things will done.

I'm against adding an additional layer of complexity for something as simple as a rebalance/rewrite, but fine. I think this is one of those things that should be included as a warning on the base README. Including steps on how to import the vanilla text as you describe, because currently I don't know how to do that and I'm sure others won't either. I would also suggest maybe adding a line about it to the output in the console, so new users understand that this is expected and don't start panicking. 

>This assertion needs to be discussed more broadly. At least I personally don't agree with that.

I admit to being a little heated when I said that, I apologise and I could have communicated it better. My frustration is that such a drastic change in normal operation occured with no warning. I don't think a normal user would expect to have all default dialogue just suddenly wiped, especially if they're coming from the old community skill system. Though given how you don't have a large audience for this skill system yet, I suppose it makes sense you wouldn't have said anything abou it.

**Comment by MokhaLeee** [comment]
Alright, I thought it would be a matter of course to crop out this part of the space. Now that there is opposition, there is now a config to decide for itself how to install it:

https://github.com/MokhaLeee/fe8u-cskillsys-kernel/pull/178
