### ISSUE TITLE
DoubleLion not functioning as intended

### ISSUE THREAD

**Issue by JesterWizard** [MokhaLeee/fe8u-cskillsys-kernel#200]
Likely as a result of the recent rewrite of `BattleOrder.c` among other things, but DoubleLion no longer applies a x4 boost. It's now functioning like the `Fighter` skills and seems to be dependant on the `basic_judgement` which is a consierable change in how the skill operates. I was able to get it to work like it did originally but my version doesn't display the blue number.

![image](https://github.com/user-attachments/assets/949ff9d8-3efb-408c-9cf4-3c53ff6c130f)

**Comment by MokhaLeee** [comment]
https://github.com/MokhaLeee/fe8u-cskillsys-kernel/commit/406188af3d64cd16e4fff21e7b64af1bd6a18b44

**Comment by MokhaLeee** [comment]
what means "display the blue number"?

**Comment by JesterWizard** [comment]
> what means "display the blue number"?

This blue number 

![36-00990021735.png](https://github.com/user-attachments/assets/8bdabea9-7989-4343-8041-b3fd745c23ef)

**Comment by MokhaLeee** [comment]
LOL the palette difference was not considered when I wrote battle-forcast code. This can be thrown off the todo list
