### ISSUE TITLE
Status conditions only lasting 1 turn?

### ISSUE THREAD

**Issue by JesterWizard** [MokhaLeee/fe8u-cskillsys-kernel#205]
Status conditions are now only lasting 1 turn regardless of how many turns they have been set for. Units simply heal on their next turn. I've seen this happen for both enemy and allies, regardless of whether I set the status via a skill or RAM hack it.

**Comment by MokhaLeee** [comment]
For the `UNIT_STAT_DEBUFF_IDX`, yes they can only keey one turn. If you try to edit them via FEB patch, you will find that the stat-debuff is not allowed to set duration.

For the `UNIT_STATUS_IDENTIFIER`, they can keep no more than 4 turns

**Comment by JesterWizard** [comment]
I can see why you do this from a balancing perspective (like petrify), but it does make some stauses like poison effectively useless in the process.

**Comment by MokhaLeee** [comment]
posion should hold its duration. will that status directly vanish berfore its duration decrease to 0?

**Comment by JesterWizard** [comment]
Small correction, they do take damage before they heal but yes the poison status effect is just one turn. Same as the others.
