### ISSUE TITLE
Status Conditions - Mini Mug Box vs Stat Screen

### ISSUE THREAD

**Issue by JesterWizard** [MokhaLeee/fe8u-cskillsys-kernel#21]
I noticed you've changed how status conditions in the status byte are handled.

A consequence of this (that you might already be aware of) is that the number of turns isn't consistent between the Mini Mug Box and the Stat Screen. 

Mini Mug Box
![image](https://github.com/MokhaLeee/fe8u-cskillsys-kernel/assets/164426396/49dfb458-54e4-4b4e-8011-a8080421f9de)

Stat Screen
![image](https://github.com/MokhaLeee/fe8u-cskillsys-kernel/assets/164426396/b81167f8-3d2f-465d-ba7b-9153883d37ee)

**Comment by MokhaLeee** [comment]
https://github.com/MokhaLeee/fe8u-cskillsys-kernel/commit/88e3055225021391a2b39a8ae785f507df80e5aa

fixed
