### ISSUE TITLE
ConBonus not applying

### ISSUE THREAD

**Issue by JesterWizard** [MokhaLeee/fe8u-cskillsys-kernel#229]
![image](https://github.com/user-attachments/assets/84a50f74-104e-4121-a0cf-2b77fe4396de)
![image](https://github.com/user-attachments/assets/c1d40631-8fc4-40d4-b107-d32762edcbf6)
![image](https://github.com/user-attachments/assets/8e5827aa-69ab-4a80-b089-b7f4c9f0c4e0)
![image](https://github.com/user-attachments/assets/62ddb0f0-fc18-42b0-b0c4-a1b3e7ce62ea)
![image](https://github.com/user-attachments/assets/43c211cd-5992-4630-8fe5-607455d787a3)

**Comment by MokhaLeee** [comment]
Yes, no con-getter are in implement. That need a lot of hooks. I thought about it and decided not to apply such hacks to such a goal of little significance。

**Comment by JesterWizard** [comment]
Well shit, another skill to go on the scrap heap for now then. :(
