### ISSUE TITLE
Magic Dust also doesn't appear to work

### ISSUE THREAD

**Issue by JesterWizard** [MokhaLeee/fe8u-cskillsys-kernel#270]
The usability check fails when I go to use it.

![image](https://github.com/user-attachments/assets/69a67432-d1d6-4a26-a365-74889c9d7804)

**Comment by MokhaLeee** [comment]
https://github.com/MokhaLeee/fe8u-cskillsys-kernel/commit/7b78b662f4e2329cbd83ab1b0965ae053a182517
