### ISSUE TITLE
AI Decision time has massively inflated

### ISSUE THREAD

**Issue by JesterWizard** [MokhaLeee/fe8u-cskillsys-kernel#330]
It's something that was only brought to my attention recently, but the time enemy units spend idling as they calculate the ideal target has inflated between 7-10 seconds, on your most recent commit. 

I suspect ``AiAttemptOffensiveAction`` to be a subject of interest, but it's way over my head to debug the cycle usage and number of calls and see what the actual problem is.

**Comment by Veslyquix** [comment]
For Pokemblem, I limited AiAttemptOffensiveAction to look at the first 3-6 targetable units instead of every possible unit. I also put MapAddInRange into iwram and called it as arm code to save on cycles. There are also a number of procs that sleep for some frames when targetting units. 

https://github.com/Veslyquix/Pokemblem/tree/master/Patches/Speedup

Hope this helps.

**Comment by MokhaLeee** [comment]
Optimization on AI decide is an interesting problem, and I will look at how to improve its performance later.

**Comment by MokhaLeee** [comment]
https://github.com/MokhaLeee/fe8u-cskillsys-kernel/pull/332

I have pulled a commit on AI decision optimization:

1. Introduce FEB patch FillAIDangerMap20220712
2. Follow the idea from Vesly to directly break the loop after get enough enemies.
3. Reduce function calling on weapon-range.

You can test the new version, I think the performance will be optimized quite a lot.

**Comment by JesterWizard** [comment]
I'll give it a try, thanks

**Comment by JesterWizard** [comment]
It won't compile for me. The dmp isn't generated. 
 
 `` *** No rule to make target '/home/username/C-SkillSystem-Mokha/Wizardry/Core/AiHack/AiOptimization/FillAIDangerMap20220712/FillAIDangerMap-7743.dmp', needed by '/home/username/C-SkillSystem-Mokha/fe8-kernel-dev.gba'.  Stop.``

**Comment by JesterWizard** [comment]
Okay figured it out. I just needed to make the dmp myself. 

Yeah this is much faster, 0.5-1 second per AI unit decision.

**Comment by MokhaLeee** [comment]
I see, makefile need updating

**Comment by MokhaLeee** [comment]
I think the main issue is the numerous calls to external functions, including skill-tester, power-getter mov-getter and weapon-range getter. Maybe later we need to further optimize such external hooks.
