### ISSUE TITLE
Combat arts causes crash

### ISSUE THREAD

**Issue by JesterWizard** [MokhaLeee/fe8u-cskillsys-kernel#334]
When attacking an enemy with battle animations turned on and a combat art enabled, the game will crash.

**Comment by MokhaLeee** [comment]
I"m not sure, but there is no problem under my test? which skill or combatart may cause error? Could you put a gif?

**Comment by JesterWizard** [comment]
@MokhaLeee 

Marisa Vs Vigarde, default configuration latest commit (1506 commits at the time of writing)


https://github.com/user-attachments/assets/7eda34dc-91bb-4692-ab40-e67d10f0165e

**Comment by MokhaLeee** [comment]
well.... Mine works fine??
![1](https://github.com/user-attachments/assets/8b249646-4be3-47dc-8554-2733a2eb9827)

Is there any modifications or is the latest commit right?

![image](https://github.com/user-attachments/assets/d47f7ea2-03e5-4ee2-a2bd-1e01d8d9ff24)

**Comment by JesterWizard** [comment]
![image](https://github.com/user-attachments/assets/9b0989fd-27e0-4c03-9417-9a0a3681d7d0)
Same as you

**Comment by MokhaLeee** [comment]
is it also crashed in No$GBA? if so, you can try it and let me see the register and stacks values

**Comment by JesterWizard** [comment]
It crashes straight out of nocash, so I can't get anything.

**Comment by MokhaLeee** [comment]
have you tried to make clean before build?

**Comment by JesterWizard** [comment]
Yep, no change

**Comment by MokhaLeee** [comment]
make CONFIG_RELEASE_COMPILATION=1
./Tools/scripts/generate_release.sh
zip -r release_dir.zip .release_dir


then give me zip

**Comment by JesterWizard** [comment]
[release_dir.zip](https://github.com/user-attachments/files/16829592/release_dir.zip)

**Comment by MokhaLeee** [comment]
well, give me ups or set make CONFIG_RELEASE_COMPILATION=1 to generate bsdiff so that I can get the rom

**Comment by JesterWizard** [comment]
I'm out right now. Will have to do it again later

**Comment by JesterWizard** [comment]
I don't understand the error generated from CONFIG_RELEASE_COMPILATION=1

I thought because the zip was generated anyway it wasn't a problem.

Anyway, here's the UPS patch.
[fe8-kernel-dev.zip](https://github.com/user-attachments/files/16829787/fe8-kernel-dev.zip)



![image](https://github.com/user-attachments/assets/708c4534-6abf-4450-b66e-6ee5aa931a43)
