### ISSUE TITLE
[Suggestion] Add SkillTable-weapon skills to the status menu

### ISSUE THREAD

**Issue by JesterWizard** [MokhaLeee/fe8u-cskillsys-kernel#336]
Currently, skills that are equipped to weapons don't show in the unit's status menu. Can this be included?

**Comment by MokhaLeee** [comment]
There is no particularly good way at present, maybe we can change the basic system in the future

**Comment by JesterWizard** [comment]
So turns out I wasn't entirely correct. Skills equipped to items are fine (which can include weapons as it happens). It's just the weapons C file specifically that doesn't show equipped skills in the stat menu. Odd.
