### ISSUE TITLE
ShrinkConvoyItemList - Adding junk data?

### ISSUE THREAD

**Issue by JesterWizard** [MokhaLeee/fe8u-cskillsys-kernel#338]
I think there might be something dodgy with the `ShrinkConvoyItemList `function, as when I call `RemoveItemFromConvoy` function the list is growing. 

Before removal
![image](https://github.com/user-attachments/assets/2889ac65-a5da-40ce-9952-80869cc53303)

After removal
![image](https://github.com/user-attachments/assets/4995349f-ee86-44cd-8da6-00caf8c1ea63)

**Comment by JesterWizard** [comment]
Okay I've been made aware that ``ShrinkConvoyItemList`` is indeed a broken mess and have been redirected to this fix for it

https://github.com/Veslyquix/Pokemblem/blob/adc2e2680ba9a3029a695d248d83ef1e4e5d8a4b/Patches/BugFixes/ShrinkConvoy.asm#L4

**Comment by JesterWizard** [comment]
Better solution 

![image](https://github.com/user-attachments/assets/277eb02c-b7ad-44a7-a6a0-b02631c6d6ac)

**Comment by MokhaLeee** [comment]
i think the problem liesin the last CpuCopy?

**Comment by JesterWizard** [comment]
Yeah to simplify the `i` in the CpuCopy needs to be changed to `(bufferIt - buffer)`. That fixes the function
