### ISSUE TITLE
[Question] data type of BU_CHG_MAG()

### ISSUE THREAD

**Issue by JesterWizard** [MokhaLeee/fe8u-cskillsys-kernel#343]
Technically both a question and a potential issue. 

Is there any reason why ``BU_CHG_MAG(bu)`` is defined as an unsigned char when all the other unit stats are signed?

I just randomly noticed when I was making a level up skill.

**Comment by MokhaLeee** [comment]
Yes, i think is this a bug, it should be s8

**Comment by MokhaLeee** [comment]
https://github.com/MokhaLeee/fe8u-cskillsys-kernel/pull/344
