### ISSUE TITLE
STR/MAG split has magical units keep using their MAG growth for STR

### ISSUE THREAD

**Issue by JesterWizard** [MokhaLeee/fe8u-cskillsys-kernel#345]
Saleh being a prime example. What should be his MAG growth is instead his STR growth. 

![image](https://github.com/user-attachments/assets/2a24dbc2-ae9b-4e55-8662-e2e937befa94)

**Comment by MokhaLeee** [comment]
You mean his growth is 0？ It is just because we did not give him a mag growth

**Comment by JesterWizard** [comment]
Not just that, but the current STR growth is what his MAG growth should be. So all magical units will need new STR growths as well.

**Comment by MokhaLeee** [comment]
Do you mean that there are bugs in the program, or is it just a problem with data settings? If it's just a data setting issue, I think it does not need to be repaired.

**Comment by JesterWizard** [comment]
It's a data settings issue, but it does throw a massive spanner in the works for anyone wanting to use magical units in the C Skill System that doesn't have the technical know-how to fix it.

**Comment by MokhaLeee** [comment]
Shall you propose a PR to configure the original character's magic? This issue is a reasonable suggestion.

**Comment by JesterWizard** [comment]
I'll look into it sure. Last time I tried, the settings didn't apply but Eirika has a magic stat so I can probably work something out with that as a basis.

**Comment by JesterWizard** [comment]
It seems my fork has diverged too much to safety make a PR, but here are the values I decided on:

[UnitMagicInfos.zip](https://github.com/user-attachments/files/17005988/UnitMagicInfos.zip)
