### ISSUE TITLE
Skill scrolls assigned by event have a limited ID range (0-255)

### ISSUE THREAD

**Issue by JesterWizard** [MokhaLeee/fe8u-cskillsys-kernel#346]
It seems any ID over 0xFF doesn't display the right skill in-game.

![image](https://github.com/user-attachments/assets/8701da32-0057-4ca0-9b99-24d9a5f14ba8)
![image](https://github.com/user-attachments/assets/d60898e1-41d1-4432-9421-ee2b9e7f6008)

**Comment by JesterWizard** [comment]
Ah, is this because the range is limited to those skills defined in skills-equip.enum.txt?

In which case, I guess this is a technical limitation?

**Comment by MokhaLeee** [comment]
yes, this is the limitation
