### ISSUE TITLE
Unintended limitations to skill scroll functionality

### ISSUE THREAD

**Issue by JesterWizard** [MokhaLeee/fe8u-cskillsys-kernel#351]
It seems the ASMC that adds a skill scroll to a unit's inventory can't do it without first removing the skill from their skills list, which makes no sense as it's not currently on their list?

**Comment by MokhaLeee** [comment]
I don't understand what you mean. Can you say it in more detail?

**Comment by JesterWizard** [comment]
Sure, so in ``debug-event.c`` you have a function to add a skill scroll to Ephraim, but the item usability for that skill scroll is disabled unless you call ``Evt_RemoveSkill`` on the skill in that scroll before you add it into his inventory. 

I'm confused why this is necessary, as he doesn't have the skill before he learns it via scroll?

![image](https://github.com/user-attachments/assets/90999941-0e84-4de0-b61b-a54a9f6a3547)

**Comment by MokhaLeee** [comment]
because he has already learned that skill in debug mode

**Comment by JesterWizard** [comment]
But he hasn't though. As you can see from my screenshot, he learns three skills in debug mode, ``MovBonus``, ``Pass`` and ``Teleportation``. 

I went through the entire system, Fury isn't currently learned anywhere by anyone.

**Comment by MokhaLeee** [comment]
https://github.com/MokhaLeee/fe8u-cskillsys-kernel/blob/main/Wizardry/Core/SkillSys/kernel/LoadSkill.c#L150

**Comment by JesterWizard** [comment]
Ah I think I understand now. It's available in his list of equippable skills that's why he can't learn it.

![image](https://github.com/user-attachments/assets/73c529fb-f627-44cc-b11f-aeffe803a4a6)
