### ISSUE TITLE
Opening R Text on a combat art causes all R text to display stats

### ISSUE THREAD

**Issue by Pikmin1211** [MokhaLeee/fe8u-cskillsys-kernel#6]
Before viewing combat art R text:
![fe8-kernel-beta-0](https://github.com/MokhaLeee/fe8u-cskillsys-kernel/assets/43188110/a636539a-da01-4fdc-bfe0-07d1c166b5bb)
Open combat art R text:
![fe8-kernel-beta-1](https://github.com/MokhaLeee/fe8u-cskillsys-kernel/assets/43188110/fd5f4151-9b9b-4d76-9ac3-4472570ff9a8)
Afterwards:
![fe8-kernel-beta-2](https://github.com/MokhaLeee/fe8u-cskillsys-kernel/assets/43188110/1f5f737a-d07f-4cb2-8d99-aecba5e044dc)
This seems to happen on any R text

**Comment by MokhaLeee** [comment]
I think I have found the reason, later I may fix it

**Comment by MokhaLeee** [comment]
now fixed https://github.com/MokhaLeee/fe8u-cskillsys-kernel/pull/10
