### ISSUE TITLE
MovGetter Status not increasing?

### ISSUE THREAD

**Issue by JesterWizard** [MokhaLeee/fe8u-cskillsys-kernel#84]
So I noticed when trying to make EvenFooted that the MovGetter doesn't seem to apply any boosts from skills.

As you can see below, I added the EvenFooted skill to both the SpdGetter and MovGetter files, but only the boost for SpdGetter is applied. 

![image](https://github.com/MokhaLeee/fe8u-cskillsys-kernel/assets/164426396/f034140d-690a-4acf-9887-5c76ed3bf64d)
![image](https://github.com/MokhaLeee/fe8u-cskillsys-kernel/assets/164426396/d8885995-af4b-4329-833a-d89ad97a3b66)

![image](https://github.com/MokhaLeee/fe8u-cskillsys-kernel/assets/164426396/727ac853-c28c-4a34-b113-ab6fe6b7d44d)

**Comment by MokhaLeee** [comment]
fixed by https://github.com/MokhaLeee/fe8u-cskillsys-kernel/commit/645945529101182f3d1b4d738dae039a706c60c3

**Comment by JesterWizard** [comment]
Defintely an improvement, but it doesn't show as a green boost, rather it shows as a natural one?

Eirika's movement should be 5 + 1 instead of a flat 6.

![image](https://github.com/MokhaLeee/fe8u-cskillsys-kernel/assets/164426396/b097db35-c232-44bb-b130-157aca9ba132)

**Comment by JesterWizard** [comment]
This has been fixed with [17cfc32](https://github.com/MokhaLeee/fe8u-cskillsys-kernel/commit/17cfc324140302329ef01237542f37e412740615)
