### ISSUE TITLE
CON boosting skill not working

### ISSUE THREAD

**Issue by JesterWizard** [MokhaLeee/fe8u-cskillsys-kernel#88]
In a similar vein to my last issue, it seems CON boosting skills are having some issues as well. Eirika has a skill called `Heavy Metal ` applied that should be boosting her CON by +5.

I've added the relevant function inside `ConGetter.c` and added the corresponding POIN in `UnitStatusGetter.event` but the skill isn't applying. What else could be missing?

![image](https://github.com/MokhaLeee/fe8u-cskillsys-kernel/assets/164426396/e2b8ee40-36be-4a47-a384-19670f357ad7)
![image](https://github.com/MokhaLeee/fe8u-cskillsys-kernel/assets/164426396/cd2a5d4e-5712-4fe2-987e-6712dc3c82fe)

![image](https://github.com/MokhaLeee/fe8u-cskillsys-kernel/assets/164426396/57f04d5d-7ddd-45ac-a8a4-b45bca578335)

**Comment by MokhaLeee** [comment]
There has no hooks injected for ConGetter since there is no "con" in Three Houses, which is just the functionality template for cskillsys. Later maybe we will insert the hooks or directly remove the ConGetter.

**Comment by JesterWizard** [comment]
Okay then, for the time being I'll close if it isn't intended to be added at this point.
