### ISSUE TITLE
Hawkeye  - INT16_MAX value displaying in stat screen

### ISSUE THREAD

**Issue by JesterWizard** [MokhaLeee/fe8u-cskillsys-kernel#90]
I really think there should be an upper limit in place for how high the battle hit rate (and the other stats by extension) are allowed to go when displayed in the stat screen. Personally, I think anything over 999 should display as "--".

Otherwise you get this

![image](https://github.com/MokhaLeee/fe8u-cskillsys-kernel/assets/164426396/24bfca65-974a-4d85-b3a4-f7d49f7b7332)

**Comment by MokhaLeee** [comment]
https://github.com/MokhaLeee/fe8u-cskillsys-kernel/commit/90bbe83788d4acfdd8499c7e6659f9ec8c792786

**Comment by MokhaLeee** [comment]
Maybe for now it has been fixed

**Comment by JesterWizard** [comment]
In the case of Hawkeye, this has introduced visual glitches for the hit rate in battle.

![image](https://github.com/MokhaLeee/fe8u-cskillsys-kernel/assets/164426396/1b56a4e0-e4b9-48b0-86e4-b8f147ccfc16)

**Comment by MokhaLeee** [comment]
https://github.com/MokhaLeee/fe8u-cskillsys-kernel/commit/d1ffbf75aafa50da4ea0ce6dec865732e60d3e2e
